package com.revature.service;

public class ManagerService {
	//TODO BONUS: LET MANAGER MAKE EMPLOYEE ACCOUNTS
	
	//TODO BONUS: LET MANAGER FIRE EMPLOYEES
	
	//TODO BONUS: LET MANAGER VIEW LOG OF ALL ACTIONS TAKEN IN APP
}
